work_dir: ./work_dir/ntu-60/xsub/PAT-Net_joint

# feeder
feeder: feeder.feeder_ntu.Feeder
train_feeder_args:
  data_path: ./data/ntu/NTU60_CS.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  data_path: ./data/ntu/NTU60_CS.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

# model
model: model.model.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [60,90]
warm_up_epoch: 5

# training
device: [0,1]
batch_size: 64
test_batch_size: 32
num_epoch: 120
nesterov: True
